### ISSUE TITLE
Error on scheme access

### ISSUE THREAD

**Issue by AlwxSin** [underyx/aiohttp-sentry#12]
Hi, thanks for your library.

I encountered a bug when my ws connection closed. If my app tries to write into closed connection `concurrent.futures._base.CancelledError` raised. And this is ok.
But then aiohttp-sentry doesn't send an error to sentry because of

```
Traceback (most recent call last):
  ......
  File "/usr/local/lib/python3.6/site-packages/aiohttp_sentry/__init__.py", line 27, in middleware
    extra_data = await self.get_extra_data(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_sentry/__init__.py", line 39, in get_extra_data
    'scheme': request.scheme,
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_request.py", line 290, in scheme
    if self.transport.get_extra_info('sslcontext'):
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

I found the related [issue](https://github.com/aio-libs/aiohttp/issues/816) but it seems closed.

Would you mind me create PR where I move `request.scheme` under `if request.transport` statement?

**Comment by underyx** [comment]
Thank you so much for the investigative work, @alwxsin! Indeed if this is how aiohttp works, we should move the scheme line as you described, like in this similar commit: https://github.com/underyx/aiohttp-sentry/commit/d7080a8199bc44d5d0021ad45079728b1369adba

A pull request would be appreciated. Thank you again!

**Comment by AlwxSin** [comment]
Done.
Thanks for quick answer.
